version: '3'
services:
  app:
    container_name: sample-bank
    restart: always
    build:
     context: .
     args:
      - DT_RELEASE_VERSION=${DT_RELEASE_VERSION}
    ports:
      - '3000:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
